### ISSUE TITLE
Convert to userstyle.

### ISSUE THREAD

**Issue by obvRedwolf** [eldritch-theme/duckduckgo#1]
Userstyles are a lot easier to manage then JS scripts as it can be managed in extensions such as Stylus.
It can also add more customizability as CSS is used opposed to JS and how users can select settings during installation. 
Userstyles should be the current standard for changing the appearance of sites.

https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by neonvoidx** [comment]
I agree with that, but this is easier for duckduckgo specifically as duckduckgo uses cookies and or url query params and not css variables
